services:
  db:
    image: postgres:17-alpine
    container_name: postgres-db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    command:
      "postgres -c 'max_connections=100'"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    
  web:
    build: .
    command: "./bin/rails server"
    env_file:
      - .env
    volumes:
      - ./app_storage:/rails/storage
    ports:
      - 3000:3000
    depends_on:
      - db