services:
  db:
    image: postgres:17-alpine
    container_name: postgres-db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    command:
      "postgres -c 'max_connections=100'"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  redis:
    image: redis:7.4-alpine
    container_name: redis
    volumes:
      - ./redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
  web:
    build: .
    command: "./bin/rails server"
    restart: always
    env_file:
      - .env
    volumes:
      - ./app_storage:/rails/storage
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
      - sidekiq
  sidekiq:
    build: .
    command: bundle exec sidekiq
    env_file:
      - .env
    volumes:
      - ./app_storage:/rails/storage
    depends_on:
      - redis